sudo: required
services:
   - docker
before_install:
# instaling gcloud sdk and updating path
   - curl https://sdk.cloud.google.com | bash > /dev/null;
   - source $HOME/google-cloud-sdk/path.bash.inc
# upa  
   - gcloud components update kubectl
   - gcloud auth activate-service-account --key-file service-account.json
   